apiVersion: apps/v1
kind: Deployment
metadata:
  name: easylink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: easylink
  template:
    metadata:
      labels:
        app: easylink
    spec:
      containers:
        - name: easylink
          image: kr812345/easylink:v0.2
          ports:
            - containerPort: 3000
